# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data-meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61ta-meta.proto\x12\x16\x63om.tsingj.me.api.core\"6\n\x08\x45ndpoint\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x10\n\x08hostname\x18\x03 \x01(\t\"@\n\tEndpoints\x12\x33\n\tendpoints\x18\x01 \x03(\x0b\x32 .com.tsingj.me.api.core.Endpoint\"H\n\x04\x44\x61ta\x12\x0e\n\x06isNull\x18\x01 \x01(\x08\x12\x14\n\x0chostLanguage\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\">\n\x0cRepeatedData\x12.\n\x08\x64\x61talist\x18\x01 \x03(\x0b\x32\x1c.com.tsingj.me.api.core.Data\"m\n\x0b\x43\x61llRequest\x12\x0f\n\x07isAsync\x18\x01 \x01(\x08\x12\x0f\n\x07timeout\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\x12+\n\x05param\x18\x04 \x01(\x0b\x32\x1c.com.tsingj.me.api.core.Data\"x\n\x0c\x43\x61llResponse\x12:\n\x0creturnStatus\x18\x01 \x01(\x0b\x32$.com.tsingj.me.api.core.ReturnStatus\x12,\n\x06result\x18\x02 \x01(\x0b\x32\x1c.com.tsingj.me.api.core.Data\"\"\n\x03Job\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"Q\n\x04Task\x12(\n\x03job\x18\x01 \x01(\x0b\x32\x1b.com.tsingj.me.api.core.Job\x12\x0e\n\x06taskId\x18\x02 \x01(\x03\x12\x0f\n\x07tableId\x18\x03 \x01(\x03\"F\n\x06Result\x12*\n\x04task\x18\x01 \x01(\x0b\x32\x1c.com.tsingj.me.api.core.Task\x12\x10\n\x08resultId\x18\x02 \x01(\x03\"-\n\x0cReturnStatus\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\tB\x0b\x42\tBasicMetab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_meta_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\tBasicMeta'
  _ENDPOINT._serialized_start=43
  _ENDPOINT._serialized_end=97
  _ENDPOINTS._serialized_start=99
  _ENDPOINTS._serialized_end=163
  _DATA._serialized_start=165
  _DATA._serialized_end=237
  _REPEATEDDATA._serialized_start=239
  _REPEATEDDATA._serialized_end=301
  _CALLREQUEST._serialized_start=303
  _CALLREQUEST._serialized_end=412
  _CALLRESPONSE._serialized_start=414
  _CALLRESPONSE._serialized_end=534
  _JOB._serialized_start=536
  _JOB._serialized_end=570
  _TASK._serialized_start=572
  _TASK._serialized_end=653
  _RESULT._serialized_start=655
  _RESULT._serialized_end=725
  _RETURNSTATUS._serialized_start=727
  _RETURNSTATUS._serialized_end=772
# @@protoc_insertion_point(module_scope)
