# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data-structure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x61ta-structure.proto\x12\x16\x63om.tsingj.me.api.core\"&\n\x08RawEntry\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\";\n\x06RawMap\x12\x31\n\x07\x65ntries\x18\x01 \x03(\x0b\x32 .com.tsingj.me.api.core.RawEntry\"i\n\x04\x44ict\x12\x34\n\x04\x64ict\x18\x01 \x03(\x0b\x32&.com.tsingj.me.api.core.Dict.DictEntry\x1a+\n\tDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x42\x0f\x42\rDataStructureb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_structure_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\rDataStructure'
  _DICT_DICTENTRY._options = None
  _DICT_DICTENTRY._serialized_options = b'8\001'
  _RAWENTRY._serialized_start=48
  _RAWENTRY._serialized_end=86
  _RAWMAP._serialized_start=88
  _RAWMAP._serialized_end=147
  _DICT._serialized_start=149
  _DICT._serialized_end=254
  _DICT_DICTENTRY._serialized_start=211
  _DICT_DICTENTRY._serialized_end=254
# @@protoc_insertion_point(module_scope)
